In [1]:
#Importing required libraries 
import re 
import numpy as np
import pandas as pd
import nltk

In [2]:
#downloading the stopwords
nltk.download('stopwords')

#collection of the stopwords is corpus
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

ps = PorterStemmer()
data = []

from nltk.stem import WordNetLemmatizer

#create an object for wordnet lemmatizer
wordnet = WordNetLemmatizer()

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\PUVANAAH\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [3]:
#reading the dataset
df = pd.read_csv("Reviews.csv")

In [4]:
df

,asin,name,rating,date,verified,title,body,helpfulVotes
0,B0000SX2UC,Janet,3,"October 11, 2005",False,"Def not best, but not worst",I had the Samsung A600 for awhile which is abs...,1.0
1,B0000SX2UC,Luke Wyatt,1,"January 7, 2004",False,Text Messaging Doesn't Work,Due to a software issue between Nokia and Spri...,17.0
2,B0000SX2UC,Brooke,5,"December 30, 2003",False,Love This Phone,"This is a great, reliable phone. I also purcha...",5.0
3,B0000SX2UC,amy m. teague,3,"March 18, 2004",False,"Love the Phone, BUT...!","I love the phone and all, because I really did...",1.0
4,B0000SX2UC,tristazbimmer,4,"August 28, 2005",False,"Great phone service and options, lousy case!",The phone has been great for every purpose it ...,1.0
...,...,...,...,...,...,...,...,...
67981,B081H6STQQ,jande,5,"August 16, 2019",False,"Awesome Phone, but finger scanner is a big mis...",I love the camera on this phone. The screen is...,1.0
67982,B081H6STQQ,2cool4u,5,"September 14, 2019",False,Simply Amazing!,I've been an Xperia user for several years and...,1.0
67983,B081H6STQQ,simon,5,"July 14, 2019",False,"great phon3, but many bugs need to fix. still ...",buy one more for my cousin,NaN
67984,B081TJFVCJ,Tobiasz Jedrysiak,5,"December 24, 2019",True,Phone is like new,Product looks and works like new. Very much re...,NaN
67985,B0825BB7SG,Owen Gonzalez,5,"December 11, 2019",False,Outstanding phone for the price,I love the size and style of this phone. It is...,NaN

In [5]:
#checking for null values
df.isnull().sum()

asin                0
name                2
rating              0
date                0
verified            0
title              14
body               21
helpfulVotes    40771
dtype: int64

In [6]:
#filling the null values 
df['body'] = df['body'].fillna('').apply (str)
df['name'] = df['name'].fillna('').apply (str)
df['title'] = df['title'].fillna('').apply (str)
df['helpfulVotes'] = df['helpfulVotes'].fillna('').apply (str)

In [7]:
#rechecking the dataset after filling 
df.isnull().sum()

asin            0
name            0
rating          0
date            0
verified        0
title           0
body            0
helpfulVotes    0
dtype: int64

In [8]:
#storing the rating values in a list
a= df['rating'].tolist()
a

[3,
 1,
 5,
 3,
 4,
 4,
 5,
 4,
 5,
 3,
 4,
 1,
 2,
 4,
 1,
 4,
 5,
 1,
 5,
 1,
 5,
 4,
 1,
 1,
 5,
 3,
 4,
 1,
 5,
 3,
 1,
 5,
 5,
 5,
 5,
 4,
 4,
 5,
 5,
 4,
 4,
 3,
 4,
 4,
 1,
 5,
 5,
 1,
 5,
 4,
 1,
 5,
 5,
 1,
 4,
 1,
 5,
 5,
 5,
 1,
 1,
 5,
 1,
 5,
 4,
 5,
 3,
 5,
 3,
 5,
 5,
 2,
 3,
 1,
 5,
 4,
 3,
 1,
 4,
 1,
 3,
 4,
 3,
 2,
 4,
 3,
 4,
 3,
 2,
 5,
 2,
 5,
 1,
 4,
 3,
 4,
 1,
 5,
 5,
 5,
 3,
 4,
 2,
 3,
 4,
 1,
 5,
 1,
 1,
 2,
 4,
 5,
 1,
 5,
 1,
 5,
 3,
 4,
 5,
 3,
 2,
 1,
 3,
 5,
 5,
 2,
 3,
 5,
 1,
 1,
 4,
 5,
 3,
 5,
 2,
 1,
 3,
 3,
 5,
 1,
 1,
 5,
 1,
 1,
 5,
 5,
 3,
 4,
 3,
 3,
 1,
 5,
 5,
 1,
 1,
 2,
 4,
 1,
 1,
 1,
 1,
 1,
 4,
 1,
 1,
 5,
 2,
 4,
 5,
 1,
 4,
 5,
 5,
 3,
 1,
 5,
 5,
 5,
 5,
 1,
 2,
 5,
 1,
 5,
 1,
 3,
 1,
 1,
 3,
 5,
 4,
 2,
 1,
 1,
 2,
 1,
 1,
 1,
 4,
 1,
 5,
 2,
 1,
 5,
 5,
 5,
 1,
 1,
 5,
 1,
 5,
 3,
 5,
 1,
 5,
 1,
 4,
 4,
 1,
 3,
 1,
 5,
 1,
 5,
 5,
 4,
 1,
 1,
 2,
 1,
 5,
 1,
 3,
 1,
 1,
 1,
 5,
 5,
 5,
 2,
 5,
 2,
 1,
 1,
 1,
 3,
 1,
 1,
 1,
 5,
 5,
 5,
 5,
 1,
 5,
 5,
 5,
 5,
 1,
 5,
 3,
 2,
 1,
 2,
 5,
 5,
 5,
 1,
 3,
 5,
 1,
 5,
 4,
 1,
 5,
 1,
 5,
 1,
 5,
 5,
 1,
 1,
 5,
 5,
 5,
 2,
 5,
 3,
 5,
 5,
 5,
 3,
 5,
 5,
 5,
 5,
 3,
 5,
 4,
 4,
 3,
 2,
 3,
 4,
 2,
 5,
 5,
 5,
 5,
 4,
 3,
 5,
 5,
 5,
 4,
 4,
 3,
 4,
 4,
 4,
 5,
 1,
 1,
 3,
 4,
 5,
 1,
 1,
 2,
 1,
 1,
 2,
 5,
 5,
 5,
 5,
 1,
 5,
 5,
 2,
 1,
 5,
 1,
 5,
 1,
 5,
 3,
 5,
 5,
 5,
 2,
 1,
 1,
 5,
 3,
 2,
 5,
 4,
 1,
 1,
 5,
 3,
 4,
 1,
 5,
 1,
 5,
 4,
 5,
 2,
 4,
 1,
 4,
 5,
 5,
 5,
 2,
 4,
 1,
 5,
 1,
 1,
 3,
 3,
 3,
 3,
 5,
 5,
 4,
 2,
 4,
 5,
 4,
 3,
 5,
 5,
 5,
 5,
 5,
 4,
 5,
 5,
 5,
 5,
 4,
 5,
 5,
 5,
 5,
 5,
 5,
 4,
 5,
 4,
 5,
 5,
 3,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 2,
 4,
 5,
 5,
 5,
 1,
 4,
 5,
 5,
 5,
 5,
 5,
 5,
 4,
 4,
 4,
 5,
 1,
 2,
 5,
 5,
 4,
 4,
 2,
 4,
 4,
 1,
 4,
 4,
 4,
 5,
 5,
 1,
 5,
 2,
 5,
 2,
 1,
 4,
 5,
 5,
 5,
 5,
 4,
 5,
 5,
 5,
 1,
 3,
 5,
 5,
 5,
 5,
 1,
 4,
 2,
 5,
 3,
 5,
 5,
 1,
 3,
 5,
 5,
 5,
 1,
 1,
 5,
 5,
 5,
 4,
 5,
 3,
 5,
 4,
 5,
 5,
 5,
 5,
 5,
 5,
 4,
 5,
 3,
 4,
 5,
 5,
 5,
 4,
 5,
 5,
 4,
 5,
 3,
 1,
 5,
 4,
 5,
 1,
 1,
 3,
 5,
 1,
 2,
 5,
 5,
 2,
 5,
 3,
 1,
 5,
 5,
 1,
 2,
 5,
 3,
 1,
 1,
 3,
 5,
 5,
 3,
 3,
 1,
 1,
 5,
 5,
 1,
 3,
 5,
 5,
 1,
 5,
 5,
 1,
 5,
 5,
 5,
 5,
 4,
 5,
 5,
 5,
 3,
 5,
 5,
 5,
 3,
 4,
 5,
 5,
 3,
 5,
 1,
 1,
 5,
 5,
 5,
 4,
 5,
 5,
 5,
 3,
 5,
 2,
 5,
 5,
 1,
 5,
 5,
 5,
 5,
 5,
 5,
 4,
 5,
 5,
 5,
 4,
 5,
 1,
 5,
 4,
 5,
 5,
 5,
 5,
 5,
 4,
 1,
 5,
 5,
 5,
 5,
 5,
 4,
 5,
 5,
 1,
 5,
 5,
 4,
 4,
 5,
 1,
 5,
 3,
 5,
 5,
 5,
 5,
 2,
 4,
 5,
 5,
 5,
 5,
 3,
 5,
 5,
 5,
 5,
 1,
 4,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 2,
 3,
 2,
 5,
 5,
 5,
 5,
 5,
 3,
 1,
 5,
 4,
 5,
 2,
 5,
 5,
 4,
 5,
 4,
 5,
 5,
 1,
 3,
 4,
 1,
 3,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 1,
 4,
 5,
 5,
 2,
 1,
 5,
 5,
 5,
 1,
 5,
 4,
 5,
 1,
 1,
 1,
 1,
 1,
 4,
 5,
 3,
 1,
 1,
 2,
 5,
 5,
 4,
 1,
 5,
 5,
 5,
 4,
 1,
 5,
 3,
 5,
 4,
 1,
 5,
 5,
 1,
 1,
 1,
 4,
 3,
 5,
 4,
 5,
 1,
 5,
 5,
 4,
 4,
 5,
 1,
 4,
 5,
 5,
 1,
 5,
 5,
 5,
 4,
 5,
 1,
 5,
 1,
 1,
 5,
 1,
 2,
 1,
 1,
 1,
 5,
 4,
 1,
 5,
 3,
 5,
 5,
 5,
 3,
 4,
 1,
 2,
 5,
 4,
 5,
 3,
 5,
 5,
 1,
 5,
 4,
 5,
 2,
 5,
 4,
 3,
 1,
 5,
 5,
 5,
 1,
 4,
 1,
 5,
 2,
 1,
 1,
 3,
 3,
 5,
 5,
 2,
 2,
 5,
 4,
 1,
 1,
 1,
 2,
 5,
 1,
 5,
 5,
 4,
 5,
 5,
 4,
 5,
 5,
 2,
 1,
 4,
 2,
 2,
 1,
 3,
 1,
 3,
 5,
 5,
 4,
 4,
 5,
 5,
 5,
 1,
 1,
 5,
 3,
 5,
 2,
 1,
 2,
 5,
 4,
 1,
 1,
 2,
 1,
 1,
 5,
 5,
 1,
 4,
 1,
 3,
 5,
 1,
 4,
 1,
 1,
 5,
 1,
 5,
 3,
 5,
 5,
 1,
 2,
 4,
 1,
 1,
 1,
 3,
 2,
 2,
 4,
 5,
 2,
 3,
 1,
 2,
 2,
 2,
 1,
 1,
 2,
 2,
 1,
 2,
 3,
 1,
 3,
 5,
 5,
 5,
 4,
 1,
 4,
 4,
 5,
 5,
 1,
 5,
 3,
 5,
 1,
 4,
 5,
 5,
 4,
 4,
 1,
 1,
 1,
 5,
 2,
 5,
 1,
 5,
 3,
 4,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 4,
 5,
 5,
 1,
 5,
 5,
 1,
 1,
 1,
 5,
 5,
 3,
 5,
 5,
 5,
 1,
 5,
 5,
 3,
 4,
 5,
 5,
 3,
 5,
 5,
 4,
 5,
 5,
 5,
 5,
 1,
 1,
 1,
 5,
 5,
 4,
 4,
 5,
 3,
 3,
 4,
 5,
 4,
 4,
 5,
 3,
 3,
 5,
 4,
 5,
 4,
 1,
 1,
 1,
 1,
 4,
 1,
 5,
 3,
 5,
 1,
 5,
 3,
 4,
 ...]

In [9]:
#assining 1 to rating no from 1 to 3(positive) and the rest as 0(negative) 
d =[]
for i in range(len(a)):
    if a[i] >=3:
        d.append(1)
    else:
        d.append(0)

d

[1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 ...]

In [10]:
#joining columns, title and body
df['Review'] = df[['title','body']].agg(' '.join, axis =1)
df.head()

,asin,name,rating,date,verified,title,body,helpfulVotes,Review
0,B0000SX2UC,Janet,3,"October 11, 2005",False,"Def not best, but not worst",I had the Samsung A600 for awhile which is abs...,1.0,"Def not best, but not worst I had the Samsung ..."
1,B0000SX2UC,Luke Wyatt,1,"January 7, 2004",False,Text Messaging Doesn't Work,Due to a software issue between Nokia and Spri...,17.0,Text Messaging Doesn't Work Due to a software ...
2,B0000SX2UC,Brooke,5,"December 30, 2003",False,Love This Phone,"This is a great, reliable phone. I also purcha...",5.0,"Love This Phone This is a great, reliable phon..."
3,B0000SX2UC,amy m. teague,3,"March 18, 2004",False,"Love the Phone, BUT...!","I love the phone and all, because I really did...",1.0,"Love the Phone, BUT...! I love the phone and a..."
4,B0000SX2UC,tristazbimmer,4,"August 28, 2005",False,"Great phone service and options, lousy case!",The phone has been great for every purpose it ...,1.0,"Great phone service and options, lousy case! T..."

In [11]:
#making the above list as a column called emotion

dt = pd.DataFrame(d, columns = ['emotion'])
dt.head()

   emotion
0        1
1        0
2        1
3        1
4        1

In [12]:
#concatenating the newly created column with the datatset
data1 = pd.concat([df,dt], axis = 1)
data1.head()

,asin,name,rating,date,verified,title,body,helpfulVotes,Review,emotion
0,B0000SX2UC,Janet,3,"October 11, 2005",False,"Def not best, but not worst",I had the Samsung A600 for awhile which is abs...,1.0,"Def not best, but not worst I had the Samsung ...",1
1,B0000SX2UC,Luke Wyatt,1,"January 7, 2004",False,Text Messaging Doesn't Work,Due to a software issue between Nokia and Spri...,17.0,Text Messaging Doesn't Work Due to a software ...,0
2,B0000SX2UC,Brooke,5,"December 30, 2003",False,Love This Phone,"This is a great, reliable phone. I also purcha...",5.0,"Love This Phone This is a great, reliable phon...",1
3,B0000SX2UC,amy m. teague,3,"March 18, 2004",False,"Love the Phone, BUT...!","I love the phone and all, because I really did...",1.0,"Love the Phone, BUT...! I love the phone and a...",1
4,B0000SX2UC,tristazbimmer,4,"August 28, 2005",False,"Great phone service and options, lousy case!",The phone has been great for every purpose it ...,1.0,"Great phone service and options, lousy case! T...",1

In [13]:
data1.drop(columns = ['asin','name', 'rating', 'date','verified', 'title', 'body', 'helpfulVotes'], axis =1, inplace = True)

In [14]:
data1

                                                  Review  emotion
0      Def not best, but not worst I had the Samsung ...        1
1      Text Messaging Doesn't Work Due to a software ...        0
2      Love This Phone This is a great, reliable phon...        1
3      Love the Phone, BUT...! I love the phone and a...        1
4      Great phone service and options, lousy case! T...        1
...                                                  ...      ...
67981  Awesome Phone, but finger scanner is a big mis...        1
67982  Simply Amazing! I've been an Xperia user for s...        1
67983  great phon3, but many bugs need to fix. still ...        1
67984  Phone is like new Product looks and works like...        1
67985  Outstanding phone for the price I love the siz...        1

[67986 rows x 2 columns]

In [15]:
#Check data1 shape
data1.shape

(67986, 2)

In [16]:
x = data1.iloc[: ,0].values
y = data1.iloc[: ,1].values

In [17]:
#initializing empty array to append clean text

corpus = []

#no of rowa to be cleaned
for i in range(len(x)):
    
    temp = data1['Review'][i]
    
    #replacing punctuations and numbers using re library
    temp = re.sub('[^a-zA-Z]', ' ', temp)
    
    temp = re.sub(r'\d+', ' ', temp)
    
    temp = temp.replace('[^\W\s\S]', ' ')
    
    #converting all text to lower case 
    temp = temp.lower()
    
    #spliting to array( default delimeter is " ")
    temp = temp.split()
    
    #looping for Lemmatizing each word in string array
    temp = [ps.stem(word) for word in temp if not word in set(
    stopwords.words('english'))]

    #rejoining the string
    temp = ' '.join(temp)

    #append each string to create array of clean text 
    corpus.append(temp)

In [18]:
#tokenization or vectorization
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 2000)
#z contains vectorized data
z = cv.fit_transform(corpus).toarray()

In [19]:
x = cv.fit_transform(corpus).toarray()

In [20]:
x

array([[0, 0, 1, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [21]:
from sklearn.model_selection import train_test_split
#Splitting the data to train and test set
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state = 0)

In [22]:
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(54388, 2000)
(54388,)
(13598, 2000)
(13598,)

In [23]:
#importing keras libraries
import tensorflow
from tensorflow.keras.models import Sequential 
from tensorflow.keras.layers import Dense 

#building the model
model = Sequential() 
model.add(Dense(2000, kernel_initializer ='random_uniform', activation = "relu"))
model.add(Dense(4000, kernel_initializer ='random_uniform', activation = "relu"))
model.add(Dense(4000, kernel_initializer ='random_uniform', activation = "relu"))
model.add(Dense(1, kernel_initializer ='random_uniform', activation = "sigmoid"))

#to accelarate the gradient 
model.compile(optimizer = "rmsprop", loss = "binary_crossentropy", metrics = ["accuracy"])
model.fit(x_train, y_train, batch_size = 128, epochs = 10)

Epoch 1/10
425/425 [==============================] - 348s 812ms/step - loss: 0.3456 - accuracy: 0.8967
Epoch 2/10
425/425 [==============================] - 367s 864ms/step - loss: 0.1884 - accuracy: 0.9325
Epoch 3/10
425/425 [==============================] - 392s 922ms/step - loss: 0.1446 - accuracy: 0.9520
Epoch 4/10
425/425 [==============================] - 334s 786ms/step - loss: 0.1063 - accuracy: 0.9699
Epoch 5/10
425/425 [==============================] - 284s 670ms/step - loss: 0.0774 - accuracy: 0.9805
Epoch 6/10
425/425 [==============================] - 300s 705ms/step - loss: 0.0777 - accuracy: 0.9860
Epoch 7/10
425/425 [==============================] - 295s 694ms/step - loss: 0.0540 - accuracy: 0.9893
Epoch 8/10
425/425 [==============================] - 300s 706ms/step - loss: 0.0521 - accuracy: 0.9919
Epoch 9/10
425/425 [==============================] - 323s 759ms/step - loss: 0.0467 - accuracy: 0.9924
Epoch 10/10
425/425 [==============================] - 303s 713ms/step - loss: 0.0331 - accuracy: 0.9941

In [24]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense (Dense)                (None, 2000)              4002000
_________________________________________________________________
dense_1 (Dense)              (None, 4000)              8004000
_________________________________________________________________
dense_2 (Dense)              (None, 4000)              16004000
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 4001
=================================================================
Total params: 28,014,001
Trainable params: 28,014,001
Non-trainable params: 0
_________________________________________________________________

In [25]:
model.save('phone.h5')

In [27]:
text = "the phone is good"
text = re.sub('[^a-zA-Z]', ' ', text)
text = text.lower()
text = text.split()
text = [ps.stem(word) for word in text if not word in set(stopwords.words('english'))]
text = ' '.join(text)

In [28]:
ypred = model.predict(cv.transform([text]))
ypred

array([[0.975423]], dtype=float32)

In [29]:
ypred = ypred > 0.5
ypred

array([[ True]])

In [31]:
#condition is > 0.5
#negativate - false < 0.5
#positive -true > 0.5
text

'phone good'

In [35]:
text1 = "this is a very bad phone"
text1 = re.sub('[^a-zA-Z]', ' ', text)
text1 = text.lower()
text1 = text.split()
text1 = [ps.stem(word) for word in text if not word in set(stopwords.words('english'))]
text1 = ' '.join(text)

In [36]:
ypred1 = model.predict(cv.transform([text1]))
ypred1

array([[0.7054358]], dtype=float32)

In [37]:
text

'bad phone'